services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
      - .env.backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "24678:24678" # 例：ViteのHMR WebSocket用ポート
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy

  db:
    build: ./backend/db
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      DOMAINS:
        "${FRONTEND_DOMAIN} -> http://frontend:${FRONTEND_PORT}, ${BACKEND_DOMAIN} -> http://backend:${BACKEND_PORT}"
      STAGE: ${HTTPS_STAGE}
    volumes:
      - ./data/certs:/var/lib/https-portal
    restart: always
    depends_on:
      - backend
      - frontend
    
volumes:
  db_data:
    
