services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "${VUE_APP_BACKEND_URL}health"]
      interval: 15s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:8080"
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy

  db:
    build: ./backend/db
    platform: linux/arm64
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/db/my.cnf:/etc/mysql/my.cnf
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    
volumes:
  db_data:
    
