"""device_idのスキーマを36固定に変更

Revision ID: f3df54773411
Revises: e7631fb12762
Create Date: 2025-10-03 22:51:34.411587+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3df54773411'
down_revision: Union[str, None] = 'e7631fb12762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'device_id',
                    existing_type=mysql.VARCHAR(length=36),
                    type_=sa.CHAR(length=36),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'device_id',
                    existing_type=sa.CHAR(length=36),
                    type_=mysql.VARCHAR(length=36),
                    existing_nullable=False)
    # ### end Alembic commands ###
