"""デバイス名からデバイスIDへ変更

Revision ID: 4e7c8338595c
Revises: 3f6112b29494
Create Date: 2025-03-04 22:20:10.669028+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4e7c8338595c'
down_revision: Union[str, None] = '3f6112b29494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'tokens', type_='primary')
    op.alter_column('tokens', 'device', new_column_name='device_id',
                    existing_type=sa.VARCHAR(length=36), nullable=False)
    op.create_primary_key('PRIMARY', 'tokens', ['username', 'device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PRIMARY', 'tokens', type_='primary')
    op.alter_column('tokens', 'device_id', new_column_name='device',
                    existing_type=sa.VARCHAR(length=16), nullable=False)
    op.create_primary_key('PRIMARY', 'tokens', ['username', 'device'])
    # ### end Alembic commands ###
