"""incomeテーブルでボーナスとペナルティを保存しない#204

Revision ID: 41fa66e82567
Revises: e8f5948391ea
Create Date: 2026-05-13 19:39:14.513014+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41fa66e82567'
down_revision: Union[str, None] = 'e8f5948391ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'total_penalty')
    op.drop_column('incomes', 'total_bonus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('total_bonus', mysql.FLOAT(),
                  server_default=sa.text("'0'"), nullable=True))
    op.add_column('incomes', sa.Column('total_penalty', mysql.FLOAT(),
                  server_default=sa.text("'0'"), nullable=True))
    # ### end Alembic commands ###
