"""user,token関連のdbスキーマ修正

Revision ID: 166309d980fb
Revises: 41fa66e82567
Create Date: 2026-06-12 15:22:25.496055+09:00

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '166309d980fb'
down_revision: Union[str, None] = '41fa66e82567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.ENUM('admin', 'general'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=mysql.ENUM('admin', 'general'),
                    nullable=True)
    # ### end Alembic commands ###
