"""incomeテーブルの月をstrからDate型へ変換

Revision ID: e8f5948391ea
Revises: f3df54773411
Create Date: 2026-05-07 20:11:10.196220+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8f5948391ea'
down_revision: Union[str, None] = 'f3df54773411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incomes", sa.Column("income_month", sa.Date(), nullable=True))
    op.execute("""
        UPDATE incomes
        SET income_month = STR_TO_DATE(CONCAT(TRIM(`year_month`), '-01'), '%Y-%c-%d')
        WHERE 'year_month' IS NOT NULL
    """)
    conn = op.get_bind()
    invalid_count = conn.execute(sa.text("""
        SELECT COUNT(*)
        FROM incomes
        WHERE 'year_month' IS NOT NULL
        AND 'income_month' IS NULL
    """)).scalar()

    if invalid_count:
        raise ValueError(f"income_month への変換に失敗したレコードが {invalid_count} 件あります")

    op.alter_column(
        "incomes",
        "income_month",
        existing_type=sa.Date(),
        nullable=False
    )
    op.drop_constraint("year_month", 'incomes', type_='unique')
    op.create_unique_constraint("uq_incomes_income_month_username",
                                'incomes', ['income_month', 'username'])
    op.drop_column('incomes', 'year_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('year_month', mysql.CHAR(length=7), nullable=True))
    op.execute("""
        UPDATE incomes
        SET year_month = CONCAT(
            YEAR('income_month'),
            '-',
            MONTH('income_month')
        )
        WHERE 'income_month' IS NOT NULL
    """)
    op.alter_column(
        "incomes",
        "year_month",
        existing_type=mysql.CHAR(length=7),
        nullable=False
    )
    op.drop_constraint("uq_incomes_income_month_username", 'incomes', type_='unique')
    op.create_unique_constraint("year_month", 'incomes', ['year_month', 'username'])
    op.drop_column('incomes', 'income_month')
    # ### end Alembic commands ###
