"""todoに期限設定する

Revision ID: 6858be292b00
Revises: 89511bb8c5d8
Create Date: 2024-11-09 19:18:24.030063+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6858be292b00'
down_revision: Union[str, None] = '89511bb8c5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due')
    # ### end Alembic commands ###
