"""“トークンテーブルにデバイスカラムを追加”

Revision ID: 8d3d93cec773
Revises: 84d52a54f8ab
Create Date: 2025-01-17 23:17:44.069968+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3d93cec773'
down_revision: Union[str, None] = '84d52a54f8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('device', sa.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'device')
    # ### end Alembic commands ###
