from enum import StrEnum


class ConflictCode(StrEnum):
    SALARY_ALREADY_EXISTS = "SALARY_ALREADY_EXISTS"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    TARGET_TIME_ALREADY_REGISTERED = "TARGET_TIME_ALREADY_REGISTERED"
    ACTIVITY_ALREADY_FINISHED = "ACTIVITY_ALREADY_FINISHED"
    TODO_ALREADY_FINISHED = "TODO_ALREADY_FINISHED"


class NotFoundCode(StrEnum):
    SALARY_NOT_FOUND_ERROR = "SALARY_NOT_FOUND_ERROR"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ACTIVITY_NOT_FOUND = "ACTIVITY_NOT_FOUND"
    TODO_NOT_FOUND = "TODO_NOT_FOUND"
    INQUIRY_NOT_FOUND = "INQUIRY_NOT_FOUND"


class NotAuthorizedCode(StrEnum):
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    INVALID_CURRENT_PASSWORD = "INVALID_CURRENT_PASSWORD"
    NOT_HAVE_PERMISSION = "NOT_HAVE_PERMISSION"


class BadRequestCode(StrEnum):
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    BULK_ACTIVITY_OPERATION_FAILED = "BULK_ACTIVITY_OPERATION_FAILED"
