# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('backend/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    - name: create .env
      run: |
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
        echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" >> .env
        echo "FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}" >> .env
        echo "DOCKER_PLATFORM=${{ secrets.DOCKER_PLATFORM }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "BACKEND_PORT=${{ secrets.BACKEND_PORT }}" >> .env
        echo "FRONTEND_DOMAIN=${{ secrets.FRONTEND_DOMAIN }}" >> .env
        echo "BACKEND_DOMAIN=${{ secrets.BACKEND_DOMAIN }}" >> .env
        echo "HTTPS_STAGE=${{ secrets.HTTPS_STAGE }}" >> .env

    - name: create .env.backend
      run: |
        echo "APP_ADMIN_USER=${{ secrets.APP_ADMIN_USER }}" >> .env.backend
        echo "APP_ADMIN_PASSWORD=${{ secrets.APP_ADMIN_PASSWORD }}" >> .env.backend
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env.backend
        echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env.backend
        echo "PEPPER=${{ secrets.PEPPER }}" >> .env.backend
        echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> .env.backend
        echo "REFRESH_TOKEN_EXPIRE_WEEKS=${{ secrets.REFRESH_TOKEN_EXPIRE_WEEKS }}" >> .env.backend
        echo "ENV=${{ secrets.ENV }}" >> .env.backend
        echo "LOGFILE_PATH=${{ secrets.LOGFILE_PATH }}" >> .env.backend
        echo "DEV_LOGFILE_PATH=${{ secrets.DEV_LOGFILE_PATH }}" >> .env.backend
        echo "TEST_MYSQL_DATABASE=${{ secrets.TEST_MYSQL_DATABASE }}" >> .env.backend
        echo "TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" >> .env.backend
        echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env.backend

    - name: Delete Docker Compose before start
      run: docker compose down -v
        
    - name: Start Docker
      run: |
        set -a
        source .env
        source .env.backend
        set +a
        docker compose up -d --build

    - name: Check if backend is up
      run: |
        for i in {1..30}; do
          if curl http://localhost:8000/health; then
            echo "Backend is up!"
            exit 0
          fi
          sleep 10
        done
        echo "Backend failed to start within 5 minutes."
        exit 1

    - name: Check if frontend is up
      run: |
        for i in {1..15}; do
          if curl http://localhost:8080; then
            echo "Frontend is up!"
            break
          fi
          sleep 5
        done
    
    - name: Create results directory
      run: |
        mkdir -p results/backend
        mkdir -p results/frontend
    
    - name: Test
      # バックグラウンドでbackendテスト実行
      echo "Starting backend tests..."
      (docker compose exec -T backend python -m pytest -vv --junitxml=results/test-results.xml && echo "Backend tests completed") &
      
      # バックグラウンドでfrontendテスト実行
      echo "Starting frontend tests..."
      (docker compose exec -T frontend npx vitest run --reporter=junit --outputFile=results/test-results.xml && echo "Frontend tests completed") &
      
      # 完了を待つ
      wait
        
      # 結果をコピー
      docker compose cp backend:/backend/results/test-results.xml results/backend/ || echo "Failed to copy backend results"
      docker compose cp frontend:/frontend/results/test-results.xml results/frontend/ || echo "Failed to copy frontend results"

    - name: Upload vitest test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-results
        path: results/frontend/test-results.xml
        
    - name: Docker logs
      if: failure()
      run: |
        docker compose logs
        echo "------"
        cat .env
        echo "------"
        cat .env.backend

    - name: Stop Docker Compose
      if: always()
      run: docker compose down -v

